# config/local.yaml
env: "local" # Окружение - local, dev или prod
storage_path: "postgres://postgres:mysecretpassword@localhost:5432/banner-service?sslmode=disable" # файл, в котором будет храниться наша БД
http_server: # конфигурация нашего http-сервера
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s
signingKey: "secret"

